Update trigger_top100.yml

diff --git a/.github/workflows/trigger_top100.yml b/.github/workflows/trigger_top100.yml
--- a/.github/workflows/trigger_top100.yml
+++ b/.github/workflows/trigger_top100.yml
@@ -47,25 +47,34 @@ jobs:
   # TRIGGER MAIN SBOM SCAN WORKFLOW
   # -----------------------------------------------------
   trigger:
-    needs: fetch
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        repo: ${{ fromJson(needs.fetch.outputs.repo_list) }}
+     needs: fetch
+     runs-on: ubuntu-latest
+     strategy:
+        fail-fast: false
+         matrix:
+          repo: ${{ fromJson(needs.fetch.outputs.repo_list) }}
+     steps:
+        - name: Debug token presence
+          run: |
+              if [ -z "${{ secrets.PERSONAL_TOKEN }}" ]; then
+              echo "❌ PERSONAL_TOKEN is missing"
+              exit 1
+              else
+              echo "✅ PERSONAL_TOKEN detected"
+              fi
 
-    steps:
-      - name: Trigger Conan+Trivy Workflow
-        uses: benc-uk/workflow-dispatch@v1
-        with:
-          workflow: main.yml
-          token: ${{ secrets.PERSONAL_TOKEN }}
-          ref: main
-          inputs: >-
-            {
+        - name: Trigger Conan+Trivy Workflow
+          uses: benc-uk/workflow-dispatch@v1
+          with:
+            workflow: main.yml
+            token: ${{ secrets.PERSONAL_TOKEN }}
+            ref: main
+            inputs: >-
+              {
               "src_repository": "${{ matrix.repo }}",
               "src_branch": "main",
               "conan_repository": "Noddy03/Conan_Trivy_full_SBOM_scan",
               "conan_branch": "main",
               "src_type": "${{ github.event.inputs.language }}"
-            }
+              }
+
